spring.application.name=Job Portal

#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.name=jobportal
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/jpdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.tomcat.max-part-count=50
